WINDOW_TITLE = "Pong"

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BACKGROUND_COLOR = "black"

PADDLE_SPEED = 30
PADDLE_STRETCH_WIDTH = 1
PADDLE_STRETCH_HEIGHT = 5
PADDLE_COLOR = "white"
PADDLE_OFFSET = 40
PADDLE_SHAPE = "square"
PADDLE_COLLISION_X = 20
PADDLE_COLLISION_Y = 50

LEFT_PADDLE_X = -SCREEN_WIDTH // 2 + PADDLE_OFFSET
RIGHT_PADDLE_X = SCREEN_WIDTH // 2 - PADDLE_OFFSET

BALL_SPEED = 2
BALL_RADIUS = 10
BALL_COLOR = "white"
BALL_ACCELERATION = 1.05
BALL_SHAPE = "circle"
BALL_COLOR = "white"
BALL_PADDLE_OFFSET = 15
BALL_PADDLE_COLLISION_DISTANCE = 30


ROUND_RESET_DELAY = 1

SCOREBOARD_Y = 260
SCOREBOARD_FONT = ("Courier", 24, "normal")

TEXT_COLOR = "white"

WINNING_SCORE = 10
WINNER_FONT = ("Courier", 28, "bold")
WINNER_MESSAGE_Y = 40
MESSAGE_COLOR = "white"

TOP_BORDER = SCREEN_HEIGHT // 2 - BALL_RADIUS
BOTTOM_BORDER = -TOP_BORDER
LEFT_BORDER = -SCREEN_WIDTH // 2 + BALL_RADIUS
RIGHT_BORDER = SCREEN_WIDTH // 2 - BALL_RADIUS

FPS = 60
