WINDOW_TITLE = "Pong"

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BACKGROUND_COLOR = "black"

PADDLE_SPEED = 5
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 100
PADDLE_COLOR = "white"

BALL_SPEED = 5
BALL_RADIUS = 10
BALL_COLOR = "white"

TEXT_COLOR = "white"

WINNING_SCORE = 10

TOP_BORDER = SCREEN_HEIGHT // 2 - BALL_RADIUS
BOTTOM_BORDER = -TOP_BORDER
LEFT_BORDER = -SCREEN_WIDTH // 2 + BALL_RADIUS
RIGHT_BORDER = SCREEN_WIDTH // 2 - BALL_RADIUS

FPS = 60